<Project Sdk="Microsoft.NET.Sdk.Web">
    <!--
        将 <Project Sdk="Microsoft.NET.Sdk"> 
        改为 <Project Sdk="Microsoft.NET.Sdk.Web">
    -->
    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ApplicationManifest>app.manifest</ApplicationManifest>
    </PropertyGroup>

    <ItemGroup>
        <Folder Include="Models\"/>
        <AvaloniaResource Include="Assets\**"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia"/>
        <PackageReference Include="Avalonia.Desktop"/>
        <PackageReference Include="Avalonia.Themes.Fluent"/>
        <PackageReference Include="Avalonia.Fonts.Inter"/>
        <PackageReference Include="CommunityToolkit.Mvvm"/>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\BatchProcess3.Core\BatchProcess3.Core.csproj" />
    </ItemGroup>
</Project>
